service: ProjectOne
# plugins:
#   - serverless-reqvalidator-plugin
#   - serverless-aws-documentation

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  profile: peca_private
  stackName: ProjectOne
  apiName: ProjectOne
  memorySize: 128
  endpointType: regional
  role: arn:aws:iam::016682580984:role/serverless-role

functions:
  root:
    handler: root.root
    events:
      - http:
          path: /
          method: get

  hello:
    handler: root.hello
    events:
      - http:
          path: hello
          method: get

  hello_name:
    handler: root.hello_name
    events:
      - http:
          path: hello/name/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
  hello_post:
    handler: root.hello_post
    events:
      - http:
          path: hello
          method: post