service: ProjectOne

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  profile: peca_private
  stackName: ProjectOne
  apiName: ProjectOne
  memorySize: 128
  endpointType: regional
  role: arn:aws:iam::016682580984:role/serverless-role
  deploymentBucket:
    name: serverless-dev-projectone
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: false

functions:
  users:
    handler: users.users
    events:
      - http:
          path: users
          method: get

  user_id:
    handler: users.user_id
    events:
      - http:
          path: users/id/{id}
          method: get
          request:
            parameters:
              paths:
                id: false

  user_email:
    handler: users.user_email
    events:
      - http:
          path: users/email/{email}
          method: get
          request:
            parameters:
              paths:
                email: true

  user_add:
    handler: users.user_add
    events:
      - http:
          path: users/user_add
          method: get
