service: ProjectOne
plugins:
#   - serverless-reqvalidator-plugin
#   - serverless-aws-documentation
  - serverless-vpc-plugin
  - serverless-vpc-discovery

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  profile: peca_private
  stackName: ProjectOne
  apiName: ProjectOne
  memorySize: 128
  endpointType: regional
  role: arn:aws:iam::016682580984:role/serverless-role
  deploymentBucket:
    name: serverless-dev-projectone
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: false

custom:
  vpc:
    vpcName: '${opt:env}-vpc'
    subnetNames:
      - '${opt:env}_Subnet-Core-1a'
      - '${opt:env}_Subnet-Core-1b'
      - '${opt:env}_Subnet-Core-1c'
    securityGroupNames:
      - '${opt:env}_Core_Security_Group'

functions:
  users:
    handler: users
    events:
      - http:
          path: users
          method: get
          request:
            parameters:
              paths:
                id: false
  user_id:
    handler: user
    events:
      - http:
          path: users/id/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  user_email:
    handler: user
    events:
      - http:
          path: users/email/{email}
          method: get
          request:
            parameters:
              paths:
                id: true
